Project
eksuas/DBMSystemsBenchmark pull request #5
Opened 2018-07-07 14:34 UTC by IremmB

2018-07-07 17:07 UTC, eksuas requested changes

2018-07-07 17:07 UTC, eksuas commented on proje.py
> +    return Movie_dict,director_set,actor_set
`return Data(actors, directors, movies)`

2018-07-07 17:07 UTC, eksuas commented on proje.py
> +    start=graph.begin()
```
    start=graph.begin()
    node1=Node("Movies",            # Create node for Movies by taking from Movie_dict
        id=dataset.movies['film_id'],        # And add properties into node
        title=dataset.movies['film_title'],
        released_year=dataset.movies['film_year'],
        rating=dataset.movies['film_rating'],
        genre=dataset.movies['film_genre'])
    start.merge(node1)   #Create it
```
film_genre vs yerine genre kullanabilirsin. 
Bunun dışında denemek lazım ama bunları eval fonksiyonu ile tek seferde gönderebiliriz sanırım. Onu beraber deneyelim.

2018-07-07 17:10 UTC, eksuas commented
Değişiklikleri yaptıktan sonra tekrar PR (pull request) gönderebilir misin.
En son onay alınca bunları master branch'a commitleyip sonra kaldığımız yerden devam edebiliriz.

2018-07-07 17:40 UTC, IremmB commented
Tamam hocam bakıyorum tekrar.
Teşekkürler,  iyi akşamlar



Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: Edanur Demir <notifications@github.com>
Tarih: 07.07.2018 20:10 (GMT+03:00)
Alıcı: eksuas/DBMSystemsBenchmark <DBMSystemsBenchmark@noreply.github.com>
Cc: IremmB <irem_bulut_1996@hotmail.com>, Author <author@noreply.github.com>
Konu: Re: [eksuas/DBMSystemsBenchmark] Project (#5)


Değişiklikleri yaptıktan sonra tekrar PR (pull request) gönderebilir misin.
En son onay alınca bunları master branch'a commitleyip sonra kaldığımız yerden devam edebiliriz.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/eksuas/DBMSystemsBenchmark/pull/5#issuecomment-403230051>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AjeEARgxP-G44hEVsuQNwkLTrDCtfQ7sks5uEOuNgaJpZM4VGYRC>.

2018-07-08 20:38 UTC, eksuas commented
Tamam şimdi olmuş, buraya gelmiş değişiklikler

2018-07-08 20:43 UTC, IremmB commented
Tamam o zaman sevindim hocam :)



Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: Edanur Demir <notifications@github.com>
Tarih: 08.07.2018 23:38 (GMT+03:00)
Alıcı: eksuas/DBMSystemsBenchmark <DBMSystemsBenchmark@noreply.github.com>
Cc: IremmB <irem_bulut_1996@hotmail.com>, Author <author@noreply.github.com>
Konu: Re: [eksuas/DBMSystemsBenchmark] Project (#5)


Tamam şimdi olmuş, buraya gelmiş değişiklikler

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/eksuas/DBMSystemsBenchmark/pull/5#issuecomment-403315288>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AjeEATkfCr4_g8sO3pq9yEr43cpHh6Elks5uEm20gaJpZM4VGYRC>.

2018-07-24 11:43 UTC, closed without merging